<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Matching Unbalanced Subsamples</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Hear me ROAR-R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="blog.html">Blog</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Exploring your data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="propensity-scores.html">Matching Subsamples</a>
    </li>
    <li>
      <a href="geo-info.html">Modelling multi-site data</a>
    </li>
  </ul>
</li>
<li>
  <a href="anova.html">Anova</a>
</li>
<li>
  <a href="lm-assumptions.html">LM</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    LMM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lmm-essential-tutorial.html">Essential Tutorial</a>
    </li>
    <li>
      <a href="lmm-contrasts-tutorial.html">Customising Contrasts</a>
    </li>
    <li>
      <a href="lmm-het-var.html">Modelling Heterogeneus Variance</a>
    </li>
    <li>
      <a href="result-report.html">Reporting of Results</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Matching Unbalanced Subsamples</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#initialise-session-and-data">Initialise Session and Data</a></li>
<li><a href="#display-unmatched-data">Display unmatched data</a></li>
<li><a href="#compute-propensity-scores">Compute propensity scores</a></li>
<li><a href="#compare-distribution-of-propensity-scores">Compare distribution of propensity scores</a></li>
<li><a href="#display-matched-data">Display matched data</a></li>
<li><a href="#check-balance">Check balance</a></li>
</ul>
</div>

<p>This code is inspired by indications found in HilL&amp;Gelman book “Data Analysis Using Regression and Multilevel/Hierarchical Models” <a href="https://g.co/kgs/zkuYrJ" class="uri">https://g.co/kgs/zkuYrJ</a></p>
<p>In psychology research, we are often interested in comparing groups on some characteristics of interest. However, the samples may often differ by some other characteristics that may play as a confound when we investigate the sources of the variance. One way of approaching this problem is to improve the matching between the subsample, trying to increase the overlap on certain characteristics.</p>
<p>With this approach, we calculate propensity scores for each participants and pair them, to exclude participants that do not have a match.</p>
<div id="initialise-session-and-data" class="section level1">
<h1>Initialise Session and Data</h1>
<p>The example dataframe lalonde contains data of two treatment groups with demographic information.</p>
<pre class="r"><code># install.packages(&quot;arm&quot;)
library(arm)
data(lalonde)
str(lalonde)</code></pre>
<pre><code>## &#39;data.frame&#39;:    445 obs. of  12 variables:
##  $ age    : num  37 22 30 27 33 22 23 32 22 33 ...
##  $ educ   : num  11 9 12 11 8 9 12 11 16 12 ...
##  $ black  : num  1 0 1 1 1 1 1 1 1 0 ...
##  $ hisp   : num  0 1 0 0 0 0 0 0 0 0 ...
##  $ married: num  1 0 0 0 0 0 0 0 0 1 ...
##  $ nodegr : num  1 1 0 1 1 1 0 1 0 0 ...
##  $ re74   : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ re75   : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ re78   : num  9930 3596 24910 7506 290 ...
##  $ u74    : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ u75    : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ treat  : num  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div id="display-unmatched-data" class="section level1">
<h1>Display unmatched data</h1>
<p>By visualising the data, we can see that there is an imbalance by age; for example, participants below 20 are over-represeted in the control group (treatment = 0).</p>
<pre class="r"><code>library(ggplot2)
ggplot(data=lalonde, 
       aes(x=age, 
           fill=factor(treat))) + 
  geom_histogram(col=&quot;black&quot;)</code></pre>
<p><img src="propensity-scores_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
</div>
<div id="compute-propensity-scores" class="section level1">
<h1>Compute propensity scores</h1>
<p>We estimate the probability of pertaining to the treatment group based on the participants characteristics with a binomial model (fit). We then use a function (arm::matching) to match 1 observation in the treatment==1 arm, with one most similar in the arm with treatment==0. Then we subset the original dataset based on the matched pairs of observations.</p>
<pre class="r"><code>fit &lt;- glm(treat ~ re74 + re75 + age + factor(educ) + 
            black + hisp + married + nodegr + u74 + u75, 
           data=lalonde,
            family=binomial(link=&quot;logit&quot;))
pscores &lt;- predict(fit, type=&quot;response&quot;)
matches &lt;- matching(z=lalonde$treat, score=pscores)
matched &lt;- lalonde[matches$matched,]</code></pre>
<p>Propensity scores calculated from the binomial model (each row corresponds to 1 participant):</p>
<pre class="r"><code>head(cbind(pscores))</code></pre>
<pre><code>##     pscores
## 1 0.3950195
## 2 0.2496017
## 3 0.4759244
## 4 0.3414587
## 5 0.4513412
## 6 0.3900016</code></pre>
<p>The propensity score is the probablityof being assigned to treatment==1 based on the participants characteristics. ideally, we want the two groups to be composed by individuals with the same probability of being assigned to both.</p>
<p>Matches show the indices (position in dataset) of a couple of matched observations, such as:</p>
<pre class="r"><code>ind &lt;- matches %&gt;% 
  tibble::rownames_to_column(&quot;index&quot;) %&gt;%
  select(-pairs) %&gt;%
  filter(matched==matched[1] | matched==index[1])
ind</code></pre>
<pre><code>##   index matched
## 1     1     197
## 2   197       1</code></pre>
<p>These two observations are matched together based on the similarity of the propensity score (0.394865 for observation number 197 and 0.3950195 for observation number 1).</p>
<p>The matched dataset only includes participants that can be coupled into pairs:</p>
<pre class="r"><code>nrow(matched)</code></pre>
<pre><code>## [1] 370</code></pre>
<p>We excluded 75 participants.</p>
</div>
<div id="compare-distribution-of-propensity-scores" class="section level1">
<h1>Compare distribution of propensity scores</h1>
<p>Why did we gain from the the exclusion of 75 participants? Hopefully, the subsamples overlap better with respect to the confounding variables. Let’s check the propensity scores of the matched sample.</p>
<pre class="r"><code>fit.m &lt;- glm(treat ~ re74 + re75 + age + factor(educ) + 
            black + hisp + married + nodegr + u74 + u75, 
            data=matched,
            family=binomial(link=&quot;logit&quot;))
pscores.m &lt;- predict(fit.m, type=&quot;response&quot;)</code></pre>
<pre class="r"><code>library(dplyr)
lalonde &lt;- lalonde %&gt;%
  mutate(p.scores=pscores)
matched &lt;- matched %&gt;%
  mutate(p.scores=pscores.m)
#plot the unmatched data
unm.d &lt;- ggplot(data=lalonde, 
                aes(x=p.scores, fill=factor(treat))) + 
  geom_density(col=&quot;black&quot;, alpha=0.4) + 
  labs(title=&quot;Unmatched Data&quot;) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  ylim(0,7)
#plot the matched data
m.d &lt;- ggplot(data=matched, 
              aes(x=p.scores, fill=factor(treat))) + 
  geom_density(col=&quot;black&quot;, alpha=0.4) + 
  labs(title=&quot;Matched Data&quot;) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  xlim(0,1)
# plot together
library(ggpubr)
ggarrange(unm.d, m.d, common.legend = T, legend = &quot;right&quot;)</code></pre>
<p><img src="propensity-scores_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The unmatched data displayed a partial separation based on propensity scores, meaning that the variables forming the propensity score might have easily confounded the treatment effect. This might happen in situations where participants with specific characteristics might be more easily recruited as a target/control group.</p>
</div>
<div id="display-matched-data" class="section level1">
<h1>Display matched data</h1>
<p>We can display the matched data by any of the categorical variables in the dataset, for example age. From the plot, we can see that approximately 50% of each age group is distributed in the treatment and control group for most of the groups. Participants in their 20s are not over-represented anymore in the control group.</p>
<pre class="r"><code>ggplot(data=matched, 
       aes(x=age, fill=factor(treat))) + 
  geom_histogram(col=&quot;black&quot;)</code></pre>
<p><img src="propensity-scores_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="check-balance" class="section level1">
<h1>Check balance</h1>
<p>We can display the difference in means of the matched/unmatched data.</p>
<pre class="r"><code>b.stats &lt;- balance(lalonde, matched, fit)
plot(b.stats)</code></pre>
<p><img src="propensity-scores_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre><code>## $raw
##           re74           re75            age  factor(educ)4  factor(educ)5 
##   -0.002159921    0.083863254    0.107277121   -0.087705802    0.158623414 
##  factor(educ)6  factor(educ)7  factor(educ)8  factor(educ)9 factor(educ)10 
##    0.078298987   -0.098299879   -0.118377488    0.057923710   -0.006921703 
## factor(educ)11 factor(educ)12 factor(educ)13 factor(educ)14 factor(educ)15 
##   -0.256078933   -0.072042948    0.190980849    0.138025647    0.148068395 
## factor(educ)16          black           hisp        married         nodegr 
##    0.103975049    0.103975049    0.043886611   -0.174561071    0.093640701 
##            u74            u75 
##   -0.303986439   -0.094140477 
## 
## $matched
##           re74           re75            age  factor(educ)4  factor(educ)5 
##     0.06621614     0.03835607     0.13615155     0.36978662     0.04823636 
##  factor(educ)6  factor(educ)7  factor(educ)8  factor(educ)9 factor(educ)10 
##     0.00000000     0.05324577    -0.03971374    -0.11366162     0.01499702 
## factor(educ)11 factor(educ)12 factor(educ)13 factor(educ)14 factor(educ)15 
##    -0.14431246     0.04961898     0.04280605     0.09321213     0.04139547 
## factor(educ)16          black           hisp        married         nodegr 
##     0.10397505    -0.31192515     0.00000000     0.13694015    -0.17185823 
##            u74            u75 
##    -0.03896622    -0.04858863</code></pre>
<p>The open circles represent the unmatched data; the closer the estimate to zero, the better. We can see that most difference scores improved, but some got worst, probably due to the exclusion of small categories.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
