<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Name of Your Project - Analysis and Results Report</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Hear me ROAR-R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="blog.html">Blog</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Exploring your data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="propensity-scores.html">Matching Subsamples</a>
    </li>
    <li>
      <a href="geo-info.html">Modelling multi-site data</a>
    </li>
  </ul>
</li>
<li>
  <a href="anova.html">Anova</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    LM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lm-assumptions.html">Assumptions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    LMM
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lmm-essential-tutorial.html">Essential Tutorial</a>
    </li>
    <li>
      <a href="lmm-contrasts-tutorial.html">Customising Contrasts</a>
    </li>
    <li>
      <a href="lmm-het-var.html">Modelling Heterogeneus Variance</a>
    </li>
    <li>
      <a href="result-report.html">Reporting of Results</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    ML
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="ml_ts.html">Supervised Learning with Time Series for Beginners</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Name of Your Project - Analysis and Results Report</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#list-all-the-loaded-packages">List all the loaded packages</a></li>
<li><a href="#import-and-format-data">Import and format data</a></li>
<li><a href="#preliminary-operations">Preliminary Operations</a></li>
<li><a href="#descriptive-statistics">Descriptive Statistics</a></li>
<li><a href="#main-analysis">Main Analysis</a><ul>
<li><a href="#results">Results</a><ul>
<li><a href="#model-comparison">Model Comparison</a></li>
<li><a href="#fixed-effects">Fixed Effects</a></li>
<li><a href="#random-effect">Random Effect</a></li>
<li><a href="#group-comparisons">Group Comparisons</a></li>
<li><a href="#individual-variation">Individual Variation</a></li>
<li><a href="#model-diagnostic">Model Diagnostic</a></li>
</ul></li>
</ul></li>
<li><a href="#session-info">Session Info</a></li>
</ul>
</div>

<p>Below are sections to include in a report of a Mixed Model Regression Analysis. The bullet points indicate the values that you should report. I do provide example tables of these values, and only a few, essential examples of the write-up, that’s your job to complete!</p>
<p><strong>Note that not all the sections may be applicable: it depends from your analysis pipeline!</strong></p>
<p><strong>Also, this is a list of parameters that may be sensible to include, but it does not exhaust all possibilities. You are the only fair judge of what is sensible to include/not include in your report. This is a guide made by a user, just like you</strong>.</p>
<p>Third note: the following models does not make much sense. It is just a demonstration.</p>
<pre class="r"><code>knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)</code></pre>
<div id="list-all-the-loaded-packages" class="section level1">
<h1>List all the loaded packages</h1>
<pre class="r"><code># Load packages 
packs &lt;- c(&quot;reshape2&quot;, &quot;dplyr&quot;, &quot;ggplot2&quot;, &quot;lmerTest&quot;, &quot;broom.mixed&quot;, &quot;car&quot;, &quot;knitr&quot;, &quot;stringi&quot;, &quot;tidyr&quot;, &quot;multcomp&quot;)
lapply(packs, require, character.only = TRUE)</code></pre>
<pre class="r"><code>pck &lt;- data.frame(cbind((.packages())))
names(pck) &lt;- &quot;Loaded Packages&quot;
kable(pck)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Loaded Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">tidyr</td>
</tr>
<tr class="even">
<td align="left">stringi</td>
</tr>
<tr class="odd">
<td align="left">broom.mixed</td>
</tr>
<tr class="even">
<td align="left">reshape2</td>
</tr>
<tr class="odd">
<td align="left">ggpubr</td>
</tr>
<tr class="even">
<td align="left">magrittr</td>
</tr>
<tr class="odd">
<td align="left">Hmisc</td>
</tr>
<tr class="even">
<td align="left">Formula</td>
</tr>
<tr class="odd">
<td align="left">caret</td>
</tr>
<tr class="even">
<td align="left">lattice</td>
</tr>
<tr class="odd">
<td align="left">nlme</td>
</tr>
<tr class="even">
<td align="left">gridExtra</td>
</tr>
<tr class="odd">
<td align="left">multcomp</td>
</tr>
<tr class="even">
<td align="left">TH.data</td>
</tr>
<tr class="odd">
<td align="left">survival</td>
</tr>
<tr class="even">
<td align="left">mvtnorm</td>
</tr>
<tr class="odd">
<td align="left">knitr</td>
</tr>
<tr class="even">
<td align="left">car</td>
</tr>
<tr class="odd">
<td align="left">carData</td>
</tr>
<tr class="even">
<td align="left">ggrepel</td>
</tr>
<tr class="odd">
<td align="left">jtools</td>
</tr>
<tr class="even">
<td align="left">ggplot2</td>
</tr>
<tr class="odd">
<td align="left">dplyr</td>
</tr>
<tr class="even">
<td align="left">lmerTest</td>
</tr>
<tr class="odd">
<td align="left">arm</td>
</tr>
<tr class="even">
<td align="left">lme4</td>
</tr>
<tr class="odd">
<td align="left">Matrix</td>
</tr>
<tr class="even">
<td align="left">MASS</td>
</tr>
<tr class="odd">
<td align="left">broom</td>
</tr>
<tr class="even">
<td align="left">stats</td>
</tr>
<tr class="odd">
<td align="left">graphics</td>
</tr>
<tr class="even">
<td align="left">grDevices</td>
</tr>
<tr class="odd">
<td align="left">utils</td>
</tr>
<tr class="even">
<td align="left">datasets</td>
</tr>
<tr class="odd">
<td align="left">methods</td>
</tr>
<tr class="even">
<td align="left">base</td>
</tr>
</tbody>
</table>
</div>
<div id="import-and-format-data" class="section level1">
<h1>Import and format data</h1>
<pre class="r"><code># Read Data 
# dat &lt;- read.csv(&quot;&quot;)
dat &lt;- mtcars</code></pre>
<pre class="r"><code># Data Formatting
dat.s &lt;- dat %&gt;%
  add_rownames(&quot;ID&quot;) %&gt;%
  mutate(ID=factor(paste(ID)),
         group=factor(ifelse(grepl(pattern = &quot;Merc&quot;, x = ID), 
                             &quot;Merc&quot;, 
                             &quot;Other&quot;)))
# Set up exclusion criterium
dat.f &lt;- dat.s %&gt;% filter(round(wt, 2)&gt;2.5)</code></pre>
</div>
<div id="preliminary-operations" class="section level1">
<h1>Preliminary Operations</h1>
<p>Report any excluded samples/participants.</p>
<pre class="r"><code># N of excluded samples
excl_sample &lt;- nrow(dat.s)-nrow(dat.f)
# Proportion of excluded samples
prop_excl_samples &lt;- round((nrow(dat.s)-nrow(dat.f))/nrow(dat.s), 2)
# Participants and relative number of excluded samples:
excl_trials &lt;- dat.s %&gt;%
  arrange(ID) %&gt;%
  group_by(ID, group) %&gt;%
  summarise(N=n(),
            N_excl=sum(wt&lt;2.5),
            Prop.excl=round(N_excl/N, 1)) %&gt;%
  filter(N_excl&gt;0)
# Participants dropped after criteria of selection:
excl &lt;- excl_trials %&gt;% 
  rename(&quot;N of completed trials&quot;=N, &quot;N of excluded trials&quot;=N_excl)
dropped &lt;- excl %&gt;% nrow()</code></pre>
<p>8 cars with weight &lt; 2.5 were excluded from the analysis:</p>
<pre class="r"><code>kable(excl[,-c(5)])</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">ID</th>
<th align="left">group</th>
<th align="right">N of completed trials</th>
<th align="right">N of excluded trials</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Datsun 710</td>
<td align="left">Other</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Fiat 128</td>
<td align="left">Other</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">Fiat X1-9</td>
<td align="left">Other</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Honda Civic</td>
<td align="left">Other</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">Lotus Europa</td>
<td align="left">Other</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Porsche 914-2</td>
<td align="left">Other</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">Toyota Corolla</td>
<td align="left">Other</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Toyota Corona</td>
<td align="left">Other</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
</div>
<div id="descriptive-statistics" class="section level1">
<h1>Descriptive Statistics</h1>
<p>Report essential descriptive statistics.</p>
<pre class="r"><code>#Wide to long format
dat.l &lt;- melt(dat.f,
        # ID variables - all the variables to keep but not split apart on
    id.vars=c(&quot;ID&quot;, &quot;mpg&quot;, &quot;cyl&quot;, &quot;disp&quot;, &quot;hp&quot;, &quot;drat&quot;, &quot;wt&quot;, &quot;qsec&quot;, &quot;gear&quot;, &quot;carb&quot;, &quot;group&quot;),
        # The source columns
    measure.vars=c(&quot;vs&quot;, &quot;am&quot;),
        # Name of the destination column that will identify the original
        # column that the measurement came from
    variable.name=&quot;eng-trasm&quot;,
    value.name=&quot;Value&quot;
)</code></pre>
<pre class="r"><code>mercedes &lt;- data.frame(dat.l) %&gt;% #one variable to count (may be males/females...)
  filter(group==&quot;Merc&quot;) %&gt;% 
  dplyr::select(ID) %&gt;% 
  unique() 
mercedes &lt;- mercedes$ID

descr &lt;- dat.l %&gt;%
  group_by(cyl) %&gt;%
  summarise(N=length(unique(ID)),
            N_mercedes=length(which(unique(ID) %in% mercedes)),
            m.mpg=round(mean(mpg), 2),
            min.mpg=round(min(mpg), 2),
            max.mpg=round(max(mpg), 2),
            m.qsec=round(mean(qsec), 2),
            s.qsec=round(sd(qsec), 2),
            iqr.qsec=round(IQR(qsec), 2)) %&gt;%
  t() %&gt;%
  data.frame() %&gt;%
  rename(&quot;_&quot;=X1, &quot;__&quot;=X2, &quot;___&quot;=X3)</code></pre>
<pre class="r"><code>kable(descr, caption = &quot;Table 1: descriptive statistics by cyl&quot;)</code></pre>
<table>
<caption>Table 1: descriptive statistics by cyl</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">_</th>
<th align="right">__</th>
<th align="right">___</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>cyl</td>
<td align="right">4.00</td>
<td align="right">6.00</td>
<td align="right">8.00</td>
</tr>
<tr class="even">
<td>N</td>
<td align="right">3.00</td>
<td align="right">7.00</td>
<td align="right">14.00</td>
</tr>
<tr class="odd">
<td>N_mercedes</td>
<td align="right">2.00</td>
<td align="right">2.00</td>
<td align="right">3.00</td>
</tr>
<tr class="even">
<td>m.mpg</td>
<td align="right">22.87</td>
<td align="right">19.74</td>
<td align="right">15.10</td>
</tr>
<tr class="odd">
<td>min.mpg</td>
<td align="right">21.40</td>
<td align="right">17.80</td>
<td align="right">10.40</td>
</tr>
<tr class="even">
<td>max.mpg</td>
<td align="right">24.40</td>
<td align="right">21.40</td>
<td align="right">19.20</td>
</tr>
<tr class="odd">
<td>m.qsec</td>
<td align="right">20.50</td>
<td align="right">17.98</td>
<td align="right">16.77</td>
</tr>
<tr class="even">
<td>s.qsec</td>
<td align="right">1.96</td>
<td align="right">1.64</td>
<td align="right">1.17</td>
</tr>
<tr class="odd">
<td>iqr.qsec</td>
<td align="right">3.22</td>
<td align="right">2.70</td>
<td align="right">1.76</td>
</tr>
</tbody>
</table>
</div>
<div id="main-analysis" class="section level1">
<h1>Main Analysis</h1>
<p>Report:</p>
<ul>
<li><p>Formula of the model</p></li>
<li><p>Fixed Effects</p></li>
<li><p>Random Effects. Specify varying intercept and/or slope in parentheses.</p></li>
<li><p>Method to compute p-values</p></li>
<li><p>Software, version and packages used for the analysis - such as: these analysis were carried out with R 3.5.1. The models were run using lmerTest version 3.1.2; the contrasts were calculated with the package multcomp version 1.4.8.</p></li>
</ul>
<p>Describe:</p>
<ul>
<li><p>Rationale of formula</p></li>
<li><p>Random Structure</p></li>
</ul>
<div id="results" class="section level2">
<h2>Results</h2>
<div id="model-comparison" class="section level3">
<h3>Model Comparison</h3>
<p>If you compared more than one model, report the following results.</p>
<pre class="r"><code>mod_0 &lt;- lmer(qsec ~ mpg + (1|ID), data=dat.l)
mod_1 &lt;- lmer(qsec ~ mpg + group + (1|ID), data=dat.l)
mod_2 &lt;- lmer(qsec ~ mpg * group + (1|ID), data=dat.l)</code></pre>
<p>List the models:</p>
<pre class="r"><code>mds &lt;- ls(pattern=&quot;^mod&quot;)
list_mds &lt;- data.frame(cbind(mds, 
      formula=c(paste0(formula(mds[1]))[3], 
        paste0(formula(mds[2]))[3], 
        paste0(formula(mds[3]))[3])
     ))
kable(list_mds)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">mds</th>
<th align="left">formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mod_0</td>
<td align="left">mpg + (1 | ID)</td>
</tr>
<tr class="even">
<td align="left">mod_1</td>
<td align="left">mpg + group + (1 | ID)</td>
</tr>
<tr class="odd">
<td align="left">mod_2</td>
<td align="left">mpg * group + (1 | ID)</td>
</tr>
<tr class="even">
<td align="left">model.01</td>
<td align="left">mpg + (1 | ID)</td>
</tr>
<tr class="odd">
<td align="left">model.01b</td>
<td align="left">mpg + group + (1 | ID)</td>
</tr>
<tr class="even">
<td align="left">model.01c</td>
<td align="left">mpg * group + (1 | ID)</td>
</tr>
<tr class="odd">
<td align="left">model.02</td>
<td align="left">mpg + (1 | ID)</td>
</tr>
</tbody>
</table>
<p>Report:</p>
<ul>
<li><p>Method (backward elimination, forward selection)</p></li>
<li><p>Test</p></li>
<li><p>AIC</p></li>
<li><p>BIC</p></li>
<li><p>Log Likelihood</p></li>
<li><p>Deviance</p></li>
<li><p>statistic</p></li>
<li><p>Degrees of Freedom</p></li>
<li><p>P-Value</p></li>
</ul>
<p>Comment on:</p>
<ul>
<li><p>AIC</p></li>
<li><p>Deviance</p></li>
<li><p>P-Values</p></li>
<li><p>(DoF)</p></li>
</ul>
<pre class="r"><code>m.anv &lt;- anova(mod_0,mod_1,mod_2)
m.anv &lt;- m.anv %&gt;%
  tidy() %&gt;% 
  mutate(Sign=ifelse(p.value&lt;0.001, &quot;**&quot;, 
                     ifelse(p.value&lt;0.05, &quot;*&quot;,
                            ifelse(p.value &lt; 0.1, &quot;.&quot;, &quot;-&quot;)))) %&gt;%
  mutate_each(funs(round(.,2)), -term, -Sign)</code></pre>
<pre class="r"><code>kable(m.anv, caption = &quot;Table 2: model comparison&quot;)</code></pre>
<table>
<caption>Table 2: model comparison</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">npar</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">statistic</th>
<th align="right">df</th>
<th align="right">p.value</th>
<th align="left">Sign</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mod_0</td>
<td align="right">4</td>
<td align="right">-532.97</td>
<td align="right">-525.49</td>
<td align="right">270.49</td>
<td align="right">-540.97</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">mod_1</td>
<td align="right">5</td>
<td align="right">-521.85</td>
<td align="right">-512.49</td>
<td align="right">265.92</td>
<td align="right">-531.85</td>
<td align="right">0.00</td>
<td align="right">1</td>
<td align="right">1.00</td>
<td align="left">-</td>
</tr>
<tr class="odd">
<td align="left">mod_2</td>
<td align="right">6</td>
<td align="right">-527.62</td>
<td align="right">-516.40</td>
<td align="right">269.81</td>
<td align="right">-539.62</td>
<td align="right">7.77</td>
<td align="right">1</td>
<td align="right">0.01</td>
<td align="left">*</td>
</tr>
</tbody>
</table>
</div>
<div id="fixed-effects" class="section level3">
<h3>Fixed Effects</h3>
<p>Report key findings in the text:</p>
<ul>
<li><p>Parameter estimates, Standard Errors, Confidence Intervals (and method used to calculate them), Significance tests (Estimate = , SE = , p &lt; )</p></li>
<li><p>Standard deviations and correlations of random effects</p></li>
</ul>
<p>Example of description of a model, from <em>Winter, 2013</em> (<a href="https://arxiv.org/pdf/1308.5499.pdf" class="uri">https://arxiv.org/pdf/1308.5499.pdf</a>):</p>
<p><em>“We used R (R Core Team, 2012) and lme4 (Bates, Maechler &amp; Bolker, 2012) to perform a linear mixed effects analysis of the relationship between pitch and politeness. As fixed effects, we entered politeness and gender (without interaction term) into the model. As random effects, we had intercepts for subjects and items, as well as by-subject and by-item 21 random slopes for the effect of politeness. Visual inspection of residual plots did not reveal any obvious deviations from homoscedasticity or normality. P-values were obtained by likelihood ratio tests of the full model with the effect in question against the model without the effect in question.”</em></p>
<pre class="r"><code># confidence intervals
set.seed(88)
ci &lt;- confint(mod_2, method=&quot;Wald&quot;)
ci &lt;- data.frame(ci[-c(1,2),])
ci &lt;- ci %&gt;% tibble::rownames_to_column(&quot;term&quot;)</code></pre>
<pre class="r"><code># estimates
est &lt;- data.frame(summary(mod_2)$coef)
est2 &lt;- est %&gt;% 
  add_rownames(&quot;term&quot;) %&gt;%
  inner_join(ci, by=&quot;term&quot;) %&gt;%
  rename(&quot;p.value&quot;=Pr...t..,
         &quot;st.error&quot;=Std..Error,
         &quot;CI_2.5&quot;=X2.5..,
         &quot;CI_97.5&quot;=X97.5..) %&gt;%
  mutate(Sign=ifelse(p.value&lt;0.001, &quot;**&quot;, 
                     ifelse(p.value&lt;0.05, &quot;*&quot;,
                            ifelse(p.value &lt; 0.1, &quot;.&quot;, &quot;-&quot;))),
         group=ifelse(grepl(pattern = &quot;Other&quot;, x = term), &quot;Other&quot;, &quot;Merc&quot;)) %&gt;%
  mutate_each(funs(round(.,2)), -term, -Sign, -group)</code></pre>
<pre class="r"><code>kable(est2, caption = &quot;Table 3: estimates of fixed effects and 95% confidence intervals&quot;)</code></pre>
<table>
<caption>Table 3: estimates of fixed effects and 95% confidence intervals</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">Estimate</th>
<th align="right">st.error</th>
<th align="right">df</th>
<th align="right">t.value</th>
<th align="right">p.value</th>
<th align="right">CI_2.5</th>
<th align="right">CI_97.5</th>
<th align="left">Sign</th>
<th align="left">group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">8.39</td>
<td align="right">1.84</td>
<td align="right">0.00</td>
<td align="right">4.56</td>
<td align="right">0.99</td>
<td align="right">4.79</td>
<td align="right">11.99</td>
<td align="left">-</td>
<td align="left">Merc</td>
</tr>
<tr class="even">
<td align="left">mpg</td>
<td align="right">0.55</td>
<td align="right">0.10</td>
<td align="right">0.00</td>
<td align="right">5.78</td>
<td align="right">0.99</td>
<td align="right">0.36</td>
<td align="right">0.74</td>
<td align="left">-</td>
<td align="left">Merc</td>
</tr>
<tr class="odd">
<td align="left">groupOther</td>
<td align="right">6.83</td>
<td align="right">2.22</td>
<td align="right">0.01</td>
<td align="right">3.08</td>
<td align="right">0.98</td>
<td align="right">2.48</td>
<td align="right">11.17</td>
<td align="left">-</td>
<td align="left">Other</td>
</tr>
<tr class="even">
<td align="left">mpg:groupOther</td>
<td align="right">-0.44</td>
<td align="right">0.12</td>
<td align="right">0.01</td>
<td align="right">-3.70</td>
<td align="right">0.96</td>
<td align="right">-0.68</td>
<td align="right">-0.21</td>
<td align="left">-</td>
<td align="left">Other</td>
</tr>
</tbody>
</table>
<p>For example, you would report the effect of mpg in the text: <em>“we found no significant main effect of mpg (beta = 0.55, SE = 0.10, CI 95% = 0.36 - 0.74, p-value = 0.99)”</em>. Same for the other effects and the interaction.</p>
<pre class="r"><code>plt &lt;- ggplot(subset(est2), 
                    aes(x=term, y=Estimate, fill=group, shape=group, group=term)) + 
  geom_errorbar(aes(ymin=CI_2.5, ymax=CI_97.5), width=0.1, position = position_dodge(0.5)) +
  geom_line(position = position_dodge(0.5)) +
  geom_point(size=2, position = position_dodge(0.5)) + 
  scale_shape_manual(values = c(21,22)) +
  scale_fill_manual(values=c(&quot;yellow&quot;, &quot;blue&quot;)) +
  theme(plot.subtitle = element_text(hjust=0.5), legend.position = &quot;top&quot;,
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 17),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 17),
        strip.text.x = element_text(size = 15)) +
  labs(y=&quot;Estimated qsec&quot;, x=&quot;&quot;, subtitle=&quot;&quot;)</code></pre>
<pre class="r"><code>plt</code></pre>
<p><img src="result-report_files/figure-html/unnamed-chunk-19-1.png" width="960" /></p>
</div>
<div id="random-effect" class="section level3">
<h3>Random Effect</h3>
<p>You can report the Variance or Standard Deviation of the Random Effect.</p>
<pre class="r"><code>re.id &lt;- VarCorr(mod_2, digits=2)[1]$`ID` #variance

stdev.residual &lt;- c(round(sigma(mod_2), 2)) #residual std dev

stdev.id &lt;- round(attributes(re.id)$stddev, 2) #std dev

re &lt;- tidy(rbind(stdev.id, stdev.residual))
colnames(re) &lt;- c(&quot;Term&quot;, &quot;Intercept&quot;)</code></pre>
<pre class="r"><code>kable(re, caption = &quot;Table 4: standard deviations of the random effects&quot;)</code></pre>
<table>
<caption>Table 4: standard deviations of the random effects</caption>
<thead>
<tr class="header">
<th align="left">Term</th>
<th align="right">Intercept</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">stdev.id</td>
<td align="right">1.04</td>
</tr>
<tr class="even">
<td align="left">stdev.residual</td>
<td align="right">0.00</td>
</tr>
</tbody>
</table>
</div>
<div id="group-comparisons" class="section level3">
<h3>Group Comparisons</h3>
<p>Report key findings in the text (as applicable to your specific analysis):</p>
<ul>
<li><p>T-test and Anova:</p>
<ul>
<li><p>Test statistics</p></li>
<li><p>degrees of freedom</p></li>
<li><p>significance tests</p></li>
</ul></li>
</ul>
<p>Example: Chi/F/T(df) = …, p &lt;/= …</p>
<ul>
<li><p>Simultaneous Tests for General Linear hypotheses (contrasts):</p>
<ul>
<li><p>Estimate of the test statistics</p></li>
<li><p>Standard error</p></li>
<li><p>significance test</p></li>
</ul></li>
</ul>
<p>Example: Estimate = …, SE = …, p &lt; …</p>
<div id="overall-difference-between-groups-anova" class="section level4">
<h4>Overall difference between groups (Anova)</h4>
<pre class="r"><code>overall.anv &lt;- Anova(mod_2, contrasts=list(topic=contr.sum, sys=contr.sum), type=3) %&gt;% 
  tidy() %&gt;%
  mutate(Sign=ifelse(p.value&lt;0.001, &quot;**&quot;, 
                     ifelse(p.value&lt;0.05, &quot;*&quot;,
                            ifelse(p.value &lt; 0.1, &quot;.&quot;, &quot;-&quot;)))) %&gt;%
  rename(&quot;Chisq&quot;=statistic) %&gt;%
  mutate_each(funs(round(.,2)), -term, -Sign)</code></pre>
<pre class="r"><code>kable(overall.anv, caption=&quot;Table 5 : overall difference between groups&quot;)</code></pre>
<table>
<caption>Table 5 : overall difference between groups</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">Chisq</th>
<th align="right">df</th>
<th align="right">p.value</th>
<th align="left">Sign</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">20.83</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">**</td>
</tr>
<tr class="even">
<td align="left">mpg</td>
<td align="right">33.37</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">**</td>
</tr>
<tr class="odd">
<td align="left">group</td>
<td align="right">9.49</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">*</td>
</tr>
<tr class="even">
<td align="left">mpg:group</td>
<td align="right">13.67</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="left">**</td>
</tr>
</tbody>
</table>
<p>For example, you would say in the text: <em>“the analysis of variance of type III revealed a significant difference between the groups (Chisq(1) = 9.49, p-value&lt;0.001), with the group Oter scoring higher than the Merc group (beta= 6.83, SE = 2.22; see Table 3)”</em></p>
</div>
<div id="simultaneous-tests-for-general-linear-hypotheses-between-groups-and-age-classes-contrasts" class="section level4">
<h4>Simultaneous Tests for General Linear hypotheses between groups and age classes (Contrasts)</h4>
<pre class="r"><code>group &lt;- paste0(dat.l$mpg, dat.l$group)
group &lt;- aggregate(model.matrix(mod_2) ~ group, FUN=mean)
rownames(group) &lt;- group$group
(group &lt;- group[,-1])</code></pre>
<pre><code>##           (Intercept)  mpg groupOther
## 10.4Other           1 10.4          1
## 13.3Other           1 13.3          1
## 14.3Other           1 14.3          1
## 14.7Other           1 14.7          1
## 15.2Merc            1 15.2          0
## 15.2Other           1 15.2          1
## 15.5Other           1 15.5          1
## 15.8Other           1 15.8          1
## 15Other             1 15.0          1
## 16.4Merc            1 16.4          0
## 17.3Merc            1 17.3          0
## 17.8Merc            1 17.8          0
## 18.1Other           1 18.1          1
## 18.7Other           1 18.7          1
## 19.2Merc            1 19.2          0
## 19.2Other           1 19.2          1
## 19.7Other           1 19.7          1
## 21.4Other           1 21.4          1
## 21Other             1 21.0          1
## 22.8Merc            1 22.8          0
## 24.4Merc            1 24.4          0
##           mpg:groupOther
## 10.4Other           10.4
## 13.3Other           13.3
## 14.3Other           14.3
## 14.7Other           14.7
## 15.2Merc             0.0
## 15.2Other           15.2
## 15.5Other           15.5
## 15.8Other           15.8
## 15Other             15.0
## 16.4Merc             0.0
## 17.3Merc             0.0
## 17.8Merc             0.0
## 18.1Other           18.1
## 18.7Other           18.7
## 19.2Merc             0.0
## 19.2Other           19.2
## 19.7Other           19.7
## 21.4Other           21.4
## 21Other             21.0
## 22.8Merc             0.0
## 24.4Merc             0.0</code></pre>
<p>Here I run only 1 contrast as an example between cars of group Other with mpg=10/40 and cars of group Merc with mpg=16.4.</p>
<pre class="r"><code>contrasts &lt;- rbind(
group[&quot;10.4Other&quot;,] - group[&quot;16.4Merc&quot;,]
)</code></pre>
<pre class="r"><code># Transform into Matrix
contrast.matrix &lt;- rbind(&quot;mpg 10-16 Other vs Merc&quot;=as.numeric(contrasts[1,]))
comparisons &lt;- summary(glht(mod_2, contrast.matrix))
contrasts &lt;- tidy(comparisons) %&gt;% 
  rename(&quot;term&quot;=lhs) %&gt;%
  mutate(Sign=ifelse(p.value&lt;0.001, &quot;**&quot;, 
                     ifelse(p.value&lt;0.05, &quot;*&quot;,
                            ifelse(p.value &lt; 0.1, &quot;.&quot;, &quot;-&quot;)))) %&gt;%
  mutate_each(funs(round(.,2)), -term, -Sign)</code></pre>
<pre class="r"><code>kable(contrasts[,-2], caption=&quot;Table 6: linear contrasts by group and age class&quot;)</code></pre>
<table>
<caption>Table 6: linear contrasts by group and age class</caption>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="left">Sign</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">mpg 10-16 Other vs Merc</td>
<td align="right">-1.09</td>
<td align="right">0.69</td>
<td align="right">-1.56</td>
<td align="right">0.12</td>
<td align="left">-</td>
</tr>
</tbody>
</table>
<p>Example write-up: <em>“the qsec of cars of group Other with mpg=10/40 and cars of group Merc with mpg=16.4 did not significantly differ between each other (Estimate = -1.09, SE = 0.69, p-value = 0.12)”</em></p>
</div>
</div>
<div id="individual-variation" class="section level3">
<h3>Individual Variation</h3>
<p>(Without Example)</p>
<p>Report:</p>
<ul>
<li><p>Model formula</p></li>
<li><p>Method to calculate individual coefficients/individual effect sizes (note, unrelated to model effect size!)</p></li>
<li><p>Effect sizes of key findings</p></li>
</ul>
<div id="correlations" class="section level4">
<h4>Correlations:</h4>
<ul>
<li><p>Method</p></li>
<li><p>Correlation coefficients</p></li>
</ul>
</div>
</div>
<div id="model-diagnostic" class="section level3">
<h3>Model Diagnostic</h3>
<ol style="list-style-type: decimal">
<li>Normal Quantile-Quantile (QQ) Plot (normality)</li>
</ol>
<p>The QQNorm plot shows theoretical and sample data extracted from the observed values (representative of quantiles) and aims to demonstrate that the data fits the normal distribution:</p>
<pre class="r"><code>qqnorm(resid(mod_2)) ; qqline(resid(mod_2), col=&quot;red&quot;)</code></pre>
<p><img src="result-report_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Another important diagnostic plot is the Residual Plot. Residuals are “the difference between the observed value and the estimated value of the quantity of interest (for example, a sample mean)” (from wikipedia). In the case of a regression, residuals represent the distance between the depedent variable (Reaction) and its estimates worked out by the regression function (the so-called fitted values). Plotting the residuals can demonstrate that various important assumptions are respected:</p>
<ol start="2" style="list-style-type: decimal">
<li>Histogram of the residuals (normality of the residuals)</li>
</ol>
<p>See the shape, is it normally distributed?</p>
<pre class="r"><code>hist(resid(mod_2), main = &quot;Histogram of Residuals (normality)&quot;, 
     xlab = &quot;Residuals&quot;, col = &quot;red&quot;)</code></pre>
<p><img src="result-report_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<ol start="3" style="list-style-type: decimal">
<li>Residual Plot (homogeneity)</li>
</ol>
<p>Data points should not be dispersed. We might spot some outliers.</p>
<pre class="r"><code>ggplot(data = dat.l, aes(x = predict(mod_2), y = cbind(resid(mod_2)))) + 
  geom_point(size = 3, col = &quot;red&quot;, alpha = 0.6) +
  geom_abline(slope = 0,
              intercept = 0,
              col = &quot;gray&quot;) + 
  labs(x = &quot;Fitted Values&quot;, y = &quot;Residuals&quot;, 
       title = &quot;Residuals vs Fitted&quot;, 
       subtitle = &quot;Homogeneity&quot;)</code></pre>
<p><img src="result-report_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<ol start="4" style="list-style-type: decimal">
<li>Plot of the residuals vs the independent variables (independence)</li>
</ol>
<pre class="r"><code>ggplot(data = dat.l, aes(x = group, y = cbind(resid(mod_2)))) + 
  geom_jitter(size = 3, col = &quot;red&quot;, alpha = 0.5) +
  labs(y = &quot;Residuals&quot;, title = &quot;Residuals vs Group&quot;, subtitle = &quot;Independence&quot;) </code></pre>
<p><img src="result-report_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = dat.l, aes(x = mpg, y = cbind(resid(mod_2)))) + 
  geom_jitter(size = 3, col = &quot;red&quot;, alpha = 0.5) +
  labs(y = &quot;Residuals&quot;, title = &quot;Residuals vs mpg&quot;, subtitle = &quot;Independence&quot;) </code></pre>
<p><img src="result-report_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = dat.l, aes(x = mpg, y = cbind(resid(mod_2)))) + 
  geom_jitter(size = 3, col = &quot;red&quot;, alpha = 0.5) +
  facet_wrap(~group) +
  labs(y = &quot;Residuals&quot;, title = &quot;Residuals vs group by mpg&quot;, subtitle = &quot;Independence&quot;) </code></pre>
<p><img src="result-report_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="session-info" class="section level1">
<h1>Session Info</h1>
<p>These analysis were carried out with R 3.5.1. The models were run using lmerTest version 3.1.2; the contrasts were calculated with the package multcomp version 1.4.8.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
